<?xml version="1.0" encoding="UTF-8"?>
<!--
    Original source: https://github.com/sanssecours/ABNF.tmbundle.
    Licensed under Apache 2.0. Copyright René Schwaiger.
-->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>abnf</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>ABNF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rule</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>(?:(?&lt;whitespace&gt;^[ \t]*)|[ \t]*)(?=;[[:print:]]*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>whitespace</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.abnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
			</array>
		</dict>
		<key>comment-line</key>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.abnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A line comment starts with a `;` sign and continues to the
                 end of the line.</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.semicolon.abnf</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant-decimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-hex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant-binary</string>
				</dict>
			</array>
		</dict>
		<key>constant-binary</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dash</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.abnf</string>
				</dict>
				<key>last</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-binary</string>
						</dict>
					</array>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-binary</string>
						</dict>
					</array>
				</dict>
				<key>numbers</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digits-binary-concatenation</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)%b
                # First number
                (?&lt;number&gt;[^\s.-]+)
                # Optional
                #   - dash followed by last number of range, or
                #   - sequence of additional numbers separated by dot
                (?:(?:(?=-)(?&lt;dash&gt;-)(?&lt;last&gt;\w+)) |
                   (?&lt;numbers&gt;[\w.]+))?</string>
			<key>name</key>
			<string>constant.numeric.binary.abnf</string>
		</dict>
		<key>constant-decimal</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dash</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.abnf</string>
				</dict>
				<key>last</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-decimal</string>
						</dict>
					</array>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-decimal</string>
						</dict>
					</array>
				</dict>
				<key>numbers</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digits-decimal-concatenation</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)%d
                (?&lt;number&gt;[^\s.-]+)
                (?:(?:(?=-)(?&lt;dash&gt;-)(?&lt;last&gt;\w+)) |
                   (?&lt;numbers&gt;[\w.]+))?</string>
			<key>name</key>
			<string>constant.numeric.decimal.abnf</string>
		</dict>
		<key>constant-hex</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dash</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.abnf</string>
				</dict>
				<key>last</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-hex</string>
						</dict>
					</array>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-hex</string>
						</dict>
					</array>
				</dict>
				<key>numbers</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digits-hex-concatenation</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)%x
                (?&lt;number&gt;[^\s.-]+)
                (?:(?:(?=-)(?&lt;dash&gt;-)(?&lt;last&gt;\w+)) |
                   (?&lt;numbers&gt;[\w.]+))?</string>
			<key>name</key>
			<string>constant.numeric.hex.abnf</string>
		</dict>
		<key>digit-binary</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#digit-binary-valid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#digit-binary-invalid</string>
				</dict>
			</array>
		</dict>
		<key>digit-binary-invalid</key>
		<dict>
			<key>match</key>
			<string>\S</string>
			<key>name</key>
			<string>invalid.illegal.digit.binary.abnf</string>
		</dict>
		<key>digit-binary-valid</key>
		<dict>
			<key>match</key>
			<string>[01]</string>
		</dict>
		<key>digit-decimal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#digit-decimal-valid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#digit-decimal-invalid</string>
				</dict>
			</array>
		</dict>
		<key>digit-decimal-invalid</key>
		<dict>
			<key>match</key>
			<string>\S</string>
			<key>name</key>
			<string>invalid.illegal.digit.decimal.abnf</string>
		</dict>
		<key>digit-decimal-valid</key>
		<dict>
			<key>match</key>
			<string>\d</string>
		</dict>
		<key>digit-hex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#digit-hex-valid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#digit-hex-invalid</string>
				</dict>
			</array>
		</dict>
		<key>digit-hex-invalid</key>
		<dict>
			<key>match</key>
			<string>\S</string>
			<key>name</key>
			<string>invalid.illegal.digit.hex.abnf</string>
		</dict>
		<key>digit-hex-valid</key>
		<dict>
			<key>match</key>
			<string>[0-9A-Fa-f]</string>
		</dict>
		<key>digits-binary-concatenation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dot</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.concatenation.abnf</string>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-binary</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;dot&gt;\.)(?&lt;number&gt;[^\s.]+)</string>
		</dict>
		<key>digits-decimal-concatenation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dot</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.concatenation.abnf</string>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-decimal</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;dot&gt;\.)(?&lt;number&gt;[^\s.]+)</string>
		</dict>
		<key>digits-hex-concatenation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>dot</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.concatenation.abnf</string>
				</dict>
				<key>number</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#digit-hex</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;dot&gt;\.)(?&lt;number&gt;[^\s.]+)</string>
		</dict>
		<key>operator-alternative</key>
		<dict>
			<key>match</key>
			<string>/</string>
			<key>name</key>
			<string>keyword.operator.alternative.abnf</string>
		</dict>
		<key>operator-definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator-equal-alternative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-equal</string>
				</dict>
			</array>
		</dict>
		<key>operator-equal</key>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.equal.abnf</string>
		</dict>
		<key>operator-equal-alternative</key>
		<dict>
			<key>match</key>
			<string>=/</string>
			<key>name</key>
			<string>keyword.operator.equal-alternative.abnf</string>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>(?x)^(\s*)
                 # We match the name of the rule and all following whitespace
                 # characters. We use the additional whitespace to catch a
                 # missing closing angle bracket.
                 (?&lt;name&gt;\S+\s+)
                 # The definition operator follows after the rule name.
                 (?&lt;operator&gt;\S+)
                 </string>
			<key>captures</key>
			<dict>
				<key>name</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.abnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#rule-name</string>
						</dict>
					</array>
				</dict>
				<key>operator</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#operator-definition</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>invalid.illegal.operator.abnf</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>A rule start with a possibly empty sequence of whitespace. The
                 rule continues if the next line starts with at least one more
                 whitespace character than the initial line of the rule.</string>
			<key>name</key>
			<string>meta.rule.abnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-right-side</string>
				</dict>
			</array>
			<key>while</key>
			<string>^(?=\1\s)</string>
		</dict>
		<key>rule-group</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.group.abnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.rule.group.abnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-right-side</string>
				</dict>
			</array>
		</dict>
		<key>rule-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-name-angle-brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule-name-plain</string>
				</dict>
			</array>
		</dict>
		<key>rule-name-angle-brackets</key>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.angle-bracket.abnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Angle brackets may be used around a rule name.</string>
			<key>end</key>
			<string>&gt;|(\s)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.angle-bracket.abnf</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.missing.angle-bracket.abnf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.other.rule</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-name</string>
				</dict>
			</array>
		</dict>
		<key>rule-name-core</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>rule</key>
				<dict>
					<key>name</key>
					<string>support.constant.core-rule.$1.abnf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)\b(?&lt;rule&gt;
                      ALPHA     |
                      BIT       |
                      CHAR      |
                      CR(?:LF)? |
                      CTL       |
                      DIGIT     |
                      DQUOTE    |
                      HEXDIG    |
                      HTAB      |
                      LF        |
                      LWSP      |
                      OCTECT    |
                      SP        |
                      VCHAR     |
                      WSP
                      )\b</string>
		</dict>
		<key>rule-name-plain</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>invalid</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.character.abnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>The name of a rule is a sequence of characters, beginning
                 with an alphabetic character, and followed by a combination of
                 alphabetic characters, digits, and hyphens (dashes)</string>
			<key>match</key>
			<string>[a-zA-Z][a-zA-Z0-9\-]*|(?&lt;invalid&gt;\S)</string>
			<key>name</key>
			<string>variable.other.rule.abnf</string>
		</dict>
		<key>rule-optional</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.optional.abnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.rule.optional.abnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-right-side</string>
				</dict>
			</array>
		</dict>
		<key>rule-right-side</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule-optional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-repetition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-alternative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule-name-core</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule-name</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-double-quoted-case-insensitive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted-case-sensitive</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted-case-insensitive</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;operator&gt;%i)?"</string>
			<key>captures</key>
			<dict>
				<key>operator</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.case-insensitive.abnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.case-insensitive.abnf</string>
		</dict>
		<key>string-double-quoted-case-sensitive</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;operator&gt;%s)"</string>
			<key>captures</key>
			<dict>
				<key>operator</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.case-insensitive.abnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.case-sensitive.abnf</string>
		</dict>
		<key>variable-repetition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>max</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.$max.abnf</string>
				</dict>
				<key>min</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.$min.abnf</string>
				</dict>
				<key>repetition</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.repetition.abnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variable repetition uses the syntax

                  - &lt;min&gt;*&lt;max&gt;element or
                  - &lt;repetition&gt;element

                 , where element is an ABNF element such as a group or a
                 (sub)rule. the parts in angle brackets specify a decimal
                 number. Both &lt;min&gt; and &lt;max&gt; are optional.</string>
			<key>match</key>
			<string>(?x)
               # Repetition
               (?:(?&lt;min&gt;\d*)(?&lt;repetition&gt;\*)(?&lt;max&gt;\d*) |
                  (?&lt;max&gt;\d+))
               # Followed by ABNF element
               (?=[a-zA-Z("])</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.abnf</string>
	<key>uuid</key>
	<string>7E104F42-A7B3-47CE-AE6E-D55E62C4D5E0</string>
</dict>
</plist>
