name: Java 17 Compatibility Check (for OSS-Fuzz)

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v5
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: gradle/actions/setup-gradle@v5
    - name: Build with Gradle
      run: ./gradlew lib:jar
